import { ReactNode } from 'react';
import {
  AppstoreOutlined,
  HomeOutlined,
  PauseCircleOutlined,
  AreaChartOutlined,
  NotificationOutlined,
  TeamOutlined,
  TruckOutlined,
  ProjectOutlined,
  RobotOutlined,
  UserOutlined,
  UserSwitchOutlined,
  FileSearchOutlined,
  SettingOutlined,
  UsergroupAddOutlined,
  MenuOutlined,
  ControlOutlined,
  EditOutlined,
} from '@ant-design/icons';

export const iconMap: { [key: string]: ReactNode }  = {
  appstore: <AppstoreOutlined />,
  home: <HomeOutlined />,
  pauseCircle: <PauseCircleOutlined />,
  areaChart: <AreaChartOutlined />,
  notification: <NotificationOutlined />,
  team: <TeamOutlined />,
  truck: <TruckOutlined />,
  project: <ProjectOutlined />,
  robot: <RobotOutlined />,
  user: <UserOutlined />,
  userSwitch: <UserSwitchOutlined />,
  fileSearch: <FileSearchOutlined />,
  setting: <SettingOutlined />,
  usergroupAdd: <UsergroupAddOutlined />,
  menu: <MenuOutlined />,
  control: <ControlOutlined />,
  edit: <EditOutlined />,
};