import { ReactNode } from 'react';
import {
  AppstoreOutlined,
  HomeOutlined,
  PauseCircleOutlined,
  AreaChartOutlined,
  NotificationOutlined,
  TeamOutlined,
  TruckOutlined,
  ProjectOutlined,
  RobotOutlined,
  UserOutlined,
  UserSwitchOutlined,
  FileSearchOutlined,
  SettingOutlined,
  UsergroupAddOutlined,
  MenuOutlined,
  ControlOutlined,
  EditOutlined,
  RetweetOutlined,
  PlayCircleOutlined,
  LoginOutlined,
  LogoutOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  QuestionCircleOutlined,
  MinusSquareOutlined,
  ClockCircleOutlined,
  StopOutlined,
  FormOutlined,
  UnorderedListOutlined
} from '@ant-design/icons';

export const iconMap: { [key: string]: ReactNode }  = {
  appstore: <AppstoreOutlined />,
  home: <HomeOutlined />,
  pauseCircle: <PauseCircleOutlined />,
  areaChart: <AreaChartOutlined />,
  notification: <NotificationOutlined />,
  team: <TeamOutlined />,
  truck: <TruckOutlined />,
  project: <ProjectOutlined />,
  robot: <RobotOutlined />,
  user: <UserOutlined />,
  userSwitch: <UserSwitchOutlined />,
  fileSearch: <FileSearchOutlined />,
  setting: <SettingOutlined />,
  usergroupAdd: <UsergroupAddOutlined />,
  menu: <MenuOutlined />,
  control: <ControlOutlined />,
  edit: <EditOutlined />,
  retweet: <RetweetOutlined />,
  playCircle: <PlayCircleOutlined />,
  loginIn: <LoginOutlined />,
  loginOut: <LogoutOutlined />,
  picCenter: <PicCenterOutlined />,
  picLeft: <PicLeftOutlined />,
  picRight: <PicRightOutlined />,
  questionCircle: <QuestionCircleOutlined />,
  minuSquare: <MinusSquareOutlined />,
  clockCircle: <ClockCircleOutlined />,
  stop: <StopOutlined />,
  form: <FormOutlined />,
  unorderedList: <UnorderedListOutlined />
};