export default {
  path: '/systemSettings',
  name: '系统设置',
  icon: 'setting',
  // access: 'adminRouteFilter',
  exact: true,
  routes: [
      {
          path: '/systemSettings',
          redirect: '/SystemSettings/user',
          exact: true,
      },
      {
          path: '/systemSettings/user',
          name: '用户管理',
          icon: 'usergroupAdd',
          component: './SystemSettings/user',
          // access: 'adminRouteFilter',
          exact: true,
      },
      {
          path: '/systemSettings/menu',
          name: '菜单管理',
          component: './SystemSettings/menu',
          icon: 'menu',
          // access: 'adminRouteFilter',
          exact: true,
      },
      {
        path: '/systemSettings/role',
        name: '角色管理',
        component: './SystemSettings/role',
        icon: 'control',
        // access: 'adminRouteFilter',
        exact: true,
    },
    {
      path: '/systemSettings/operationLog',
      name: '操作日志',
      component: './SystemSettings/operationLog',
      icon: 'edit',
      // access: 'adminRouteFilter',
      exact: true,
    },
  ],
}